# development docker-compose 파일
version: '3'
# services에서는 여러개의 컨테이너를 생성할수 있습니다.
services:
  backend:
    # 이미지 생성을 위해 해당 디렉토리에 있는 Dockerfile를 build한다.
    # docker-compose파일에 같은경로로 Dockerfile이 있을시 '.' 을 찍으면 된다.
    # 같은경로가 아닐시 상대경로로 지정해서 실행한다.
    build:
      context: ./
    ports:
      - '4000:3000'
